- id: my_rule1
  alias: "On Dash"
  initial_state: True 
  trigger:
    - platform: mqtt
      topic: dash/on
  action:
      service: scene.turn_on
      entity_id: scene.everything_on

- id: my_rule2
  alias: "Off Dash"
  initial_state: True 
  trigger:
    - platform: mqtt
      topic: dash/off
  action:
      service: scene.turn_on
      entity_id: scene.everything_off

- id: my_rule3
  alias: "Media player paused/stopped"
  initial_state: True 
  trigger:
    - platform: state
      entity_id: media_player.tv
      from: 'playing'
#        to: 'idle'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
      service: scene.turn_on
      entity_id: scene.livingroom_normal

- id: my_rule4
  alias: "Media player playing"
  initial_state: True 
  trigger:
    - platform: state
      entity_id: media_player.tv
      to: 'playing'
#        from: 'idle'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
      service: scene.turn_on
      entity_id: scene.livingroom_dim

- id: my_rule5
  alias: Notify Tom
  trigger:
    platform: sun
    event: sunset
  action:
    service: notify.tom
    data:
      message: 'The sun has set'

- id: my_rule6
  alias: 'Tom Away'
  initial_state: True 
  trigger:
    platform: state
    entity_id: device_tracker.android95aac635cb042bf5
    from: 'home'
    to: 'not_home'
  action:
    service: notify.tom
    data:
      message: 'Tom has left home'

  
- id: my_rule7
  alias: 'Tom Home'
  initial_state: True 
  trigger:
    platform: state
    entity_id: device_tracker.android95aac635cb042bf5
    from: 'not_home'
    to: 'home'
  action:
    service: switch.turn_on
    entity_id: switch.kitchen_light  
  
- id: my_rule8
- alias: 'Ceava Away'
  initial_state: False
  trigger:
    platform: state
    entity_id: device_tracker.moby
    from: 'home'
    to: 'not_home'
  action:
    service: notify.ceava
    data:
      message: 'Ceava has left home'

- id: my_rule9
  alias: 'Ceava Home'
  initial_state: False
  trigger:
    platform: state
    entity_id: device_tracker.moby
    from: 'not_home'
    to: 'home'
  action:
    service: notify.ceava
    data:
      message: 'Ceava is now home'
