homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 37.752393
  longitude: -122.428650
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 14
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles

# Enables the frontend
frontend:

emulated_hue:
  listen_port: 80

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  base_url: ssh.tomdee.co.uk
  ip_ban_enabled: true
  login_attempts_threshold: 5
  ssl_certificate: /etc/letsencrypt/live/ssh.tomdee.co.uk/fullchain.pem
  ssl_key: /etc/letsencrypt/live/ssh.tomdee.co.uk/privkey.pem

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:

# Text to speech
tts:
  platform: google

# Use built in mqtt server
mqtt:          

group: !include groups.yaml
automation: !include automations.yaml
scene: !include scenes.yaml
switch: !include switches.yaml

binary_sensor:
  - platform: mqtt
    state_topic: "dash/on"
    name: "On Dash"
  - platform: mqtt
    state_topic: "dash/off"
    name: "Off Dash"
  - platform: mqtt
    state_topic: "dash/wellness"
    name: "Wellness Dash"

notify:
  - name: tom
    platform: telegram
    api_key: !secret telegram
    chat_id: 170636266
  - name: ceava
    platform: telegram
    api_key: !secret telegram
    chat_id: 183773916

device_tracker:
  - platform: ubus
    track_new_devices: no
    consider_home: 300
    interval_seconds: 5
    host: 192.168.10.1
    username: root
    password: !secret router_password

apiai:
  intents:
    GetTemperature:
      speech: We have silly degrees

#camera:
#  platform: mjpeg
#  mjpeg_url: http://192.168.10.224/videostream.cgi?user=admin&pwd=09530707&resolution=32&rate=13
#  username: admin
#  password: !secret foscam_password

# TODO:
# Add some zones, like home, tom's work and ceava's work
# Add some scenes like bedtime and morning
