homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 37.752393
  longitude: -122.428650
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 14
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  base_url: ssh.tomdee.co.uk
  ip_ban_enabled: true
  login_attempts_threshold: 5
  ssl_certificate: /etc/letsencrypt/live/ssh.tomdee.co.uk/fullchain.pem
  ssl_key: /etc/letsencrypt/live/ssh.tomdee.co.uk/privkey.pem

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: yr

# Text to speech
tts:
  platform: google

group: !include groups.yaml
device_tracker:
  - platform: ubus
    track_new_devices: yes
    host: 192.168.10.1
    username: root
    password: !secret router_password

apiai:
  intents:
    GetTemperature:
      speech: We have silly degrees
